name: "Sokoban-SFML"

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4.1.1
            with:
                submodules: true
          - run: sudo apt update && sudo apt install libboost-locale-dev -y
          - run: sudo apt install libsfml-dev -y
          - run: cmake .
          - run: sudo cmake --build . --target package
          - name: Create Release
            id: create_release
            uses: actions/create-release@latest
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                tag_name: ${{ github.run_number }}
                release_name: Release ${{ github.run_number }}
                draft: false
                prerelease: false
          - name: Upload Release Asset
            id: upload-release-asset
            uses: actions/upload-release-asset@v1
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./SOKOBAN-1.0.0-Linux.deb
                asset_name: SOKOBAN-1.0.0-Linux.deb
                asset_content_type: application/vnd.debian.binary-package
                